### 기본 정보 조회
GET http://127.0.0.1:8080/basic_info?title_prefix_id=270300112&title_suffix_id=270310083&descendant_id=101000021&lang=en

### 착용중인 무기 조회
GET http://127.0.0.1:8080/weapon_entity?weapon_id=211103002&weapon_level=100&lang=en

### 장착 모듈 조회
GET http://127.0.0.1:8080/equipped_reactor?reactor_id=245001669&level=100&enchant_level=2&lang=en

### 유저 조회수 업데이트
POST http://127.0.0.1:8080/update_usercount
Content-Type: application/json
update-key: FDSearchUPDATE

{
  "username" :  "TEST"
}

### 랭킹 조회
GET http://127.0.0.1:8080/rank_list

### 착용중인 외장부품 조회
POST http://127.0.0.1:8080/equipped_external
Content-Type: application/json
lang: en

  [
    {
      "externalComponentId" : "241043004",
      "externalComponentLevel" : "100"
    },
    {
      "externalComponentId" : "242001008",
      "externalComponentLevel" : "100"
    },
    {
      "externalComponentId" : "243023002",
      "externalComponentLevel" : "100"
    },
    {
      "externalComponentId" : "244043004",
      "externalComponentLevel" : "100"
    }
  ]

### 잘못된 요청 테스트 1
GET http://127.0.0.1:8080/equipped_error?param1=HELLO&param2=WORLD
Content-Type: application/json

### 잘못된 요청 테스트 2
GET http://127.0.0.1:8080/equipped_reactor?reactor_id=245001413&level=100&enchant_level=2

### Request 카운터 테스트
GET http://127.0.0.1:8080/test

### 공지
GET 127.0.0.1:8080/get_notice
